//
//  CreateOrderInteractor.swift
//  CleanStore
//
//  Created by user on 26/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//protocol CreateOrderBusinessLogic
//{
//    func doSomething(
//        request: CreateOrder.Something.Request
//    )
//}
//protocol CreateOrderDataStore
//{
    //var name: String { get set }
//}
protocol CreateOrderInteractorInput
{
    var shippingMethods: [String] { get }
    func formatExpirationDate(
        request: CreateOrder.FormatExpirationDate.Request
    )
}
typealias CreateOrderInteractorOutput = CreateOrderPresenterInput

class CreateOrderInteractor: CreateOrderInteractorInput
//                             , CreateOrderBusinessLogic
//                             , CreateOrderDataStore
{
//MARK: - ATRIBUTES
    var shippingMethods = [
        "Standard Shipping",
        "Two-Day Shipping ",
        "One-Day Shipping "
    ]

    var output: CreateOrderInteractorOutput!
//    var worker: CreateOrderWorker!
    //var name: String = ""
    //    var presenter: CreateOrderPresentationLogic?
    
//MARK: - DO SOMETHING
    // MARK: expiration date
    func formatExpirationDate(
        request: CreateOrder.FormatExpirationDate.Request
    ) {
        let response = CreateOrder.FormatExpirationDate.Response(
            date: request.date
        )
        output.presentExpirationDate(
            response: response
        )
    }
//    func doSomething(
//        request: CreateOrder.Something.Request
//    ) {
//        worker = CreateOrderWorker()
//        worker?.doSomeWork()
//
//        let response = CreateOrder.Something.Response()
//        presenter?.presentSomething(
//            response: response
//        )
//    }
}
