//
//  CreateOrderInteractor.swift
//  CleanStore
//
//  Created by user on 26/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//protocol CreateOrderDataStore
//{
    //var name: String { get set }
//}
protocol CreateOrderBusinessLogic //same as the viewController OUTPUT
{
    var shippingMethods: [String] { get }
    func formatExpirationDate(
        request: CreateOrder.FormatExpirationDate.Request
    )
}

class CreateOrderInteractor: CreateOrderBusinessLogic//                             , CreateOrderDataStore
{
//MARK: - ATRIBUTES
    var shippingMethods = [
        "Standard Shipping",
        "Two-Day Shipping ",
        "One-Day Shipping "
    ]

    var presenter: CreateOrderPresentationLogic! // OUTPUT that goes to presenter
//    var worker: CreateOrderWorker!
    //var name: String = ""
    
//MARK: - DO SOMETHING
    // MARK: expiration date
    func formatExpirationDate(
        request: CreateOrder.FormatExpirationDate.Request
    ) {
        let response = CreateOrder.FormatExpirationDate.Response(
            date: request.date
        )
        presenter.presentExpirationDate(
            response: response
        )
    }
//    func doSomething(
//        request: CreateOrder.Something.Request
//    ) {
    // recebe o request
//        worker = CreateOrderWorker() // usa a ver q recebe o request
//        worker?.doSomeWork() // trabalha nele
//
//        let response = CreateOrder.Something.Response() //crea essa response do que volta do worker
//        presenter?.presentSomething( // envia a resposta p presenter
//            response: response
//        )
//    }
}
