//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by user on 26/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateOrder
{
  // MARK: Use cases
    enum FormatExpirationDate
    {
      struct Request // data
      {
        var date: Date
      }
      struct Response // information
      {
        var date: Date
      }
      struct ViewModel // displayFormat for the info
      {
        var date: String
      }
    }
}
