//
//  CreateOrderViewController.swift
//  CleanStore
//
//  Created by user on 26/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderDisplayLogic: AnyObject
{
    func displaySomething(
        viewModel: CreateOrder.Something.ViewModel
    )
}
protocol CreateOrderViewControllerInput
{
  func displayExpirationDate(
    viewModel: CreateOrder.FormatExpirationDate.ViewModel
  )
}
protocol CreateOrderViewControllerOutput
{
    var shippingMethods: [String] { get }
    func formatExpirationDate(
        request: CreateOrder.FormatExpirationDate.Request
    )
}

class CreateOrderViewController: UITableViewController,
                                 CreateOrderViewControllerInput,
                                 UITextFieldDelegate,
                                 UIPickerViewDelegate,
                                 UIPickerViewDataSource,
                                 CreateOrderDisplayLogic
{
    
    var output: CreateOrderViewControllerOutput!
    var interactor: CreateOrderBusinessLogic?
    var router: (NSObjectProtocol & CreateOrderRoutingLogic & CreateOrderDataPassing)?
    
    //MARK: - OUTLETS
    @IBOutlet var textFields: [UITextField]!
    
    @IBOutlet weak var shippingMethodTextField: UITextField!
    @IBOutlet var shippingMethodPicker: UIPickerView!
    
    @IBOutlet weak var expirationDateTextField: UITextField!
    @IBOutlet var expirationDatePicker: UIDatePicker!
    
    
    // MARK: Object lifecycle
    
    override init(
        nibName nibNameOrNil: String?,
        bundle nibBundleOrNil: Bundle?
    ) {
        super.init(
            nibName: nibNameOrNil,
            bundle: nibBundleOrNil
        )
        setup()
    }
    
    required init?(
        coder aDecoder: NSCoder
    ) {
        super.init(
            coder: aDecoder
        )
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = CreateOrderInteractor()
        let presenter = CreateOrderPresenter()
        let router = CreateOrderRouter()
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        
        presenter.viewController = viewController
        
        router.viewController = viewController
        router.dataStore = interactor as CreateOrderDataStore
    }
    
    
    // MARK: Routing
    override func prepare(
        for segue: UIStoryboardSegue,
        sender: Any?
    ) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(
                to: selector
            ) {
                router.perform(
                    selector,
                    with: segue
                )
            }
        }
    }
    
    // MARK: View lifecycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
        configurePickers()
        
//        doSomething()
    }
    
//MARK: - PICKERS
    func configurePickers(){ // When the user taps the shippingMethodTextField, the correct picker UI will be shown instead of the standard keyboard.
        shippingMethodTextField.inputView = shippingMethodPicker
        expirationDateTextField.inputView = expirationDatePicker
    }
    // MARK: - UIPickerViewDelegate && UIPickerViewDataSource
    func numberOfComponents(
        in pickerView: UIPickerView
    ) -> Int {
        return 1
    }
    func pickerView(
        _ pickerView: UIPickerView,
        numberOfRowsInComponent component: Int
    ) -> Int {
        return output.shippingMethods.count
    }
    func pickerView(
        _ pickerView: UIPickerView,
        titleForRow row: Int,
        forComponent component: Int
    ) -> String? {
        return output.shippingMethods[ row ]
    }
    func pickerView(
        _ pickerView: UIPickerView,
        didSelectRow row: Int,
        inComponent component: Int
    ) {
        shippingMethodTextField.text = output.shippingMethods[ row ]
    }
    //MARK: - Expiration Date
    //MARK: - CreateOrderViewControllerInput
    func displayExpirationDate(
        viewModel: CreateOrder.FormatExpirationDate.ViewModel
    ) {
        let date = viewModel.date
        expirationDateTextField.text = date
      }
    
    //MARK: - UITextFieldDelegate
    func textFieldShouldReturn( // ao pressionar o botão NEXT no Keyboard já vai direto para o próximo textField
        _ textField: UITextField
    ) -> Bool {
        textField.resignFirstResponder()
        if let index = textFields.firstIndex(
            of: textField
        ) {
            if index < textFields.count - 1 {
                let nextTextField = textFields[ index + 1 ]
                nextTextField.becomeFirstResponder()
            }
        }
        return true
    }
    
    //MARK: - TableView
    override func tableView( // quando selecionar a cell, mesmo fora do textField, já vai para a edição do textField
        _ tableView: UITableView,
        didSelectRowAt indexPath: IndexPath
    ) {
        if let cell = tableView.cellForRow(
            at: indexPath
        ) {
            for textField in textFields {
                if textField.isDescendant(
                    of: cell
                ) {
                    textField.becomeFirstResponder()
                }
            }
        }
    }
    
    // MARK: Do something
    @IBAction func expirationDatePickerValueChanged(
        _ sender: Any
    ) {
        let date = expirationDatePicker.date
        let request = CreateOrder.FormatExpirationDate.Request(
            date: date
        )
        output.formatExpirationDate(
            request: request
        )
    }
    func doSomething()
    {
        let request = CreateOrder.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(
        viewModel: CreateOrder.Something.ViewModel
    ) {
        //nameTextField.text = viewModel.name
    }
}
