//
//  ShowOrderInteractor.swift
//  CleanStore
//
//  Created by user on 28/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowOrderBusinessLogic
{
  func doSomething(request: ShowOrder.Something.Request)
}

protocol ShowOrderDataStore
{
  //var name: String { get set }
}

class ShowOrderInteractor: ShowOrderBusinessLogic, ShowOrderDataStore
{
  var presenter: ShowOrderPresentationLogic?
  var worker: ShowOrderWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowOrder.Something.Request)
  {
    worker = ShowOrderWorker()
    worker?.doSomeWork()
    
    let response = ShowOrder.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
